
const ADD_TODOS_LOADING = "ADD_TODOS_LOADING";
const ADD_TODOS_SUCCESS = "ADD_TODOS_SUCCESS";
const ADD_TODOS_ERROR = "ADD_TODOS_ERROR";
const GET_TODOS_LOADING = "GET_TODOS_LOADING";
const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
const GET_TODOS_ERROR = "GET_TODOS_ERROR";
const DEL_TODOS = "DEL_TODOS";
export {ADD_TODOS_LOADING, DEL_TODOS ,ADD_TODOS_SUCCESS, ADD_TODOS_ERROR,GET_TODOS_LOADING,GET_TODOS_SUCCESS, GET_TODOS_ERROR}